export interface SuiviJour {
  jour: number;
  titre: string;
  phase: 'moi' | 'relations' | 'projet';
  conseil: string;
  exercice: string;
}

export interface SuiviData {
  typeCode: string;
  typeName: string;
  emoji: string;
  intro: string;
  jours: SuiviJour[];
}

const db: Record<string, SuiviData> = {

  INFJ: {
    typeCode: 'INFJ', typeName: "L'Avocat", emoji: '🌙',
    intro: "En tant qu'INFJ, tu portes une vision du monde que peu partagent. Ce programme de 15 jours t'aide à mieux te comprendre, à nourrir tes relations profondes et à aligner tes ambitions avec qui tu es vraiment.",
    jours: [
      { jour:1, phase:'moi', titre:"Ton moteur secret", conseil:"Tu n'es pas motivé(e) par l'argent ou le statut — tu es guidé(e) par une mission. Sans sens, tu t'éteins lentement. Reconnaître ça te permet de n'investir ton énergie rare que là où elle crée un vrai impact.", exercice:"Liste 3 causes pour lesquelles tu travaillerais sans être payé(e). Ce sont tes vraies boussoles." },
      { jour:2, phase:'moi', titre:"Tes forces invisibles", conseil:"Tu lis les gens mieux que la plupart sans même essayer. Tu perçois les non-dits, les tensions cachées, les intentions réelles. Ce n'est pas de la sensibilité excessive — c'est une forme d'intelligence rare que tu minimises souvent.", exercice:"Rappelle-toi 1 fois où tu as 'su' quelque chose avant les autres. Qu'as-tu fait de cette information ?" },
      { jour:3, phase:'moi', titre:"Ton éponge émotionnelle", conseil:"Tu absorbes les émotions de ceux qui t'entourent sans toujours réaliser que ce que tu ressens ne t'appartient pas. Après une conversation intense, tu peux être épuisé(e) par une charge qui n'est pas la tienne.", exercice:"Après chaque interaction aujourd'hui, demande-toi : 'Est-ce que je ressentais déjà ça avant ?'" },
      { jour:4, phase:'moi', titre:"Ton masque social", conseil:"Tu souris quand tu souffres. Tu réponds 'ça va' quand ce n'est pas vrai. Ce décalage entre ce que tu ressens et ce que tu montres peut créer une solitude particulière — les gens ne savent pas que tu as besoin d'aide.", exercice:"Confie quelque chose de vrai à une personne de confiance aujourd'hui. Juste une chose." },
      { jour:5, phase:'moi', titre:"Comment tu te ressources", conseil:"La solitude de qualité — sans écran, sans obligation, sans 'devoir être disponible' — est ton carburant. Ce n'est pas de l'isolement. C'est une nécessité biologique pour ton type.", exercice:"Planifie 1h de vraie solitude cette semaine. Pas pour être productif(ve). Pour exister." },
      { jour:6, phase:'relations', titre:"Ton style de lien", conseil:"Tu préfères une amitié profonde de 3 ans à 20 connaissances. Tu peux facilement t'investir à 100% chez quelqu'un qui ne t'en donne que 30. Calibrer ton investissement à la réciprocité protège ton énergie.", exercice:"Classe tes 3 relations principales selon profondeur et réciprocité. Qu'est-ce que ça révèle ?" },
      { jour:7, phase:'relations', titre:"Ce que tu cherches", conseil:"Tu veux quelqu'un qui comprend tes silences autant que tes mots. Mais attention : tu peux idéaliser l'autre avant de le voir vraiment. Laisser l'autre se révéler progressivement évite de grandes déceptions.", exercice:"Dans ta dernière relation forte, qu'as-tu projeté sur l'autre qui n'était pas là ?" },
      { jour:8, phase:'relations', titre:"Ton point de rupture", conseil:"Tu supportes longtemps une situation qui te blesse sans rien dire — puis tu claques la porte définitivement, sans avertissement. Ce 'door slam' INFJ protège mais détruit aussi des liens réparables.", exercice:"Identifie 1 frustration actuelle non exprimée. Dis-la, doucement, à la personne concernée." },
      { jour:9, phase:'relations', titre:"Tes compatibilités", conseil:"Les ENTJ, ENFJ et ENFP te complètent souvent : ils apportent structure, action et spontanéité là où tu tends à rester dans la vision. Ce qui te manque, c'est souvent ce qu'ils incarnent naturellement.", exercice:"Pense à quelqu'un avec qui tu t'entends particulièrement bien. Qu'a-t-il que tu n'as pas ?" },
      { jour:10, phase:'relations', titre:"Comment tu aimes", conseil:"Tu aimes en actes discrets, présence totale et mémoire parfaite des détails. Tu te souviens de tout ce que l'autre t'a dit des mois plus tard. Mais tu exprimes rarement cet amour en mots directs.", exercice:"Dis à quelqu'un qui compte : 'Je t'apprécie parce que...' En mots. Pas juste en actes." },
      { jour:11, phase:'projet', titre:"Ton espace idéal", conseil:"Tu travailles mieux dans le calme, avec du temps pour réfléchir sans interruptions. Les open spaces bruyants et les réunions incessantes te consument. Ton intelligence déploie tout son potentiel quand tu as de l'espace.", exercice:"Liste 3 changements dans ton environnement de travail qui augmenteraient ta productivité immédiatement." },
      { jour:12, phase:'projet', titre:"Ton ambition secrète", conseil:"Il y a probablement quelque chose que tu veux accomplir et que tu n'oses pas dire à voix haute — quelque chose lié à l'impact, à laisser quelque chose derrière toi. Ta vision n'est pas exagérée. C'est ton chemin.", exercice:"Écris ton ambition secrète. Personne ne lira ça. Juste toi." },
      { jour:13, phase:'projet', titre:"Ton perfectionnisme", conseil:"Ton perfectionnisme n'est pas la recherche d'excellence — c'est la peur de décevoir. Tu peux passer des heures sur quelque chose de mineur parce que tu as peur que le résultat ne soit pas 'à la hauteur'. Ce n'est pas pareil.", exercice:"Nomme 1 projet bloqué. Quelle est la vraie peur derrière le 'je ne suis pas prêt(e)' ?" },
      { jour:14, phase:'projet', titre:"Ta zone de génie", conseil:"Empathie profonde + vision systémique = ton combo unique au monde. Conseil, thérapie, création de sens, leadership inspirant — partout où ces deux forces sont nécessaires ensemble, tu es irremplaçable.", exercice:"Rappelle-toi 3 moments où tu étais vraiment 'dans ton élément'. Qu'avaient-ils en commun ?" },
      { jour:15, phase:'projet', titre:"Ton prochain pas", conseil:"Ta vision ne sert personne tant qu'elle reste dans ta tête. La pensée est confortable. L'action expose. Mais le monde a besoin de ce que tu vois — pas de ce que tu penses en silence.", exercice:"Un engagement concret cette semaine : une action vers quelque chose qui compte vraiment. Même petite." },
    ],
  },

  INFP: {
    typeCode: 'INFP', typeName: 'Le Médiateur', emoji: '🌿',
    intro: "En tant qu'INFP, tu es guidé(e) par tes valeurs profondes et un monde intérieur extraordinairement riche. Ce programme t'aide à transformer ton idéalisme en force concrète, à mieux vivre tes relations et à faire de tes rêves une réalité.",
    jours: [
      { jour:1, phase:'moi', titre:"Tes valeurs comme GPS", conseil:"Tu ne fais pas les choses par obligation — tu les fais quand elles résonnent avec qui tu es. Quand tu trahis tes valeurs, même pour une bonne raison, tout en toi proteste. Apprendre à les nommer, c'est retrouver ta boussole.", exercice:"Liste tes 5 valeurs non-négociables. Comment ta vie actuelle les respecte-t-elle ?" },
      { jour:2, phase:'moi', titre:"Ton monde intérieur", conseil:"Tu as une vie intérieure extraordinairement riche que très peu voient. Ce n'est pas une faiblesse — c'est ta source créative. Le problème : garder tout ça en toi peut créer une solitude que les autres ne voient pas.", exercice:"Raconte dans un carnet quelque chose que tu n'as jamais dit à voix haute." },
      { jour:3, phase:'moi', titre:"L'idéal vs le réel", conseil:"Tu vois le monde tel qu'il devrait être. Ça t'inspire et t'épuise à la fois. L'art est de rester idéaliste dans ta vision tout en acceptant les imperfections du réel sans te laisser submerger par la déception.", exercice:"Note 1 situation où attendre la perfection t'a fait rater une belle occasion." },
      { jour:4, phase:'moi', titre:"Ton évitement du conflit", conseil:"Tu absorbes les tensions plutôt que de les nommer. Avec le temps, ça te ronge de l'intérieur. Ce que tu gardes pour toi pour 'préserver la paix' finit souvent par créer la rupture que tu cherchais à éviter.", exercice:"Cette semaine, dis doucement une vérité que tu gardes depuis trop longtemps." },
      { jour:5, phase:'moi', titre:"Ta sensibilité comme force", conseil:"Ta sensibilité n'est pas un défaut que la société dit souvent de corriger. C'est ce qui te permet de créer, de ressentir profondément et de comprendre les nuances que les autres manquent complètement.", exercice:"Liste 3 choses que ta sensibilité t'a permis de vivre ou créer que d'autres auraient ratées." },
      { jour:6, phase:'relations', titre:"Ton idéal amoureux", conseil:"Tu cherches une connexion d'âme — quelqu'un qui comprend ta complexité et partage tes valeurs. Tu peux idéaliser l'autre au point de ne plus le voir vraiment. Tomber amoureux d'une idée, pas d'une personne.", exercice:"Décris quelqu'un que tu as idéalisé. Qu'as-tu raté de réel en lui/elle ?" },
      { jour:7, phase:'relations', titre:"Ta loyauté absolue", conseil:"Quand tu t'engages dans une relation, tu donnes tout. Le problème : tout le monde ne mérite pas ce niveau d'investissement et peu peuvent le rendre. Calibrer ton investissement protège ton énergie et tes relations.", exercice:"Classe tes 3 relations importantes selon qui te redonne autant que tu donnes." },
      { jour:8, phase:'relations', titre:"Tes non-dits", conseil:"Tu évites le conflit même quand tu souffres. Mais tes non-dits finissent par exploser ou t'étouffer progressivement. Exprimer tôt et doucement une gêne évite les ruptures douloureuses plus tard.", exercice:"Identifie 1 chose que tu n'as pas dite à quelqu'un. Dis-la avec bienveillance." },
      { jour:9, phase:'relations', titre:"Tes compatibilités", conseil:"Les ENFJ, INTJ et ENTJ te complètent souvent — ils apportent structure, direction et ancrage là où tu tends à rester dans le possible. Ce qui te manque, ils le portent naturellement.", exercice:"Pense à quelqu'un qui 'te cadre' naturellement. Qu'est-ce que ça t'apporte concrètement ?" },
      { jour:10, phase:'relations', titre:"Comment tu aimes", conseil:"Tu aimes par des mots profonds, une mémoire précise de ce qui compte pour l'autre et des actes qui montrent que tu t'en es souvenu(e) longtemps après. C'est un langage d'amour rare et précieux.", exercice:"Écris une lettre — même pas envoyée — à quelqu'un qui compte. Dis ce que tu n'as pas dit." },
      { jour:11, phase:'projet', titre:"Ton travail idéal", conseil:"Tu travailles bien en autonomie, sur des projets qui ont du sens pour toi et où tu peux exprimer ta créativité. Les hiérarchies rigides, les tâches répétitives sans sens et les deadlines irréalistes t'épuisent vite.", exercice:"Décris ton environnement de travail idéal en 5 mots. Qu'est-ce qui manque aujourd'hui ?" },
      { jour:12, phase:'projet', titre:"Ta procrastination", conseil:"Tu attends souvent l'inspiration plutôt que de la créer. Tu peux rester des semaines dans ta tête sur un projet sans commencer. L'inspiration ne précède pas toujours l'action — parfois c'est l'inverse.", exercice:"Note 1 projet en suspens. Quelle est la VRAIE raison du blocage, pas la raison logique ?" },
      { jour:13, phase:'projet', titre:"Ton authenticité comme standard", conseil:"Tu n'es pas perfectionniste sur la forme — tu l'es sur l'authenticité. Le travail doit te ressembler, sinon tu bloques. Donne-toi la permission que l'imparfait-mais-vrai vaut mieux que le parfait-mais-faux.", exercice:"Soumets quelque chose d'imparfait aujourd'hui. Observe ce qu'il se passe." },
      { jour:14, phase:'projet', titre:"Ta zone de génie", conseil:"Écriture, création artistique, conseil, psychologie, enseignement — partout où l'authenticité et la profondeur humaine sont la valeur ajoutée principale. Là, tu es difficilement remplaçable.", exercice:"Liste 3 activités où le temps passe sans que tu t'en rendes compte. C'est là que tu excelles." },
      { jour:15, phase:'projet', titre:"Ton prochain pas", conseil:"L'INFP rêve grand et commence peu. Cette semaine, commence quelque chose — même petit — qui te ressemble vraiment. Un pas imparfait vers ce qui compte vaut mille plans parfaits qui restent dans la tête.", exercice:"Dédie 20 minutes cette semaine à UN projet qui te tient à cœur. Juste 20 minutes. Maintenant." },
    ],
  },

  INTJ: {
    typeCode: 'INTJ', typeName: "L'Architecte", emoji: '🏛️',
    intro: "En tant qu'INTJ, tu combines une vision à long terme avec une exigence de compétence rare. Ce programme t'aide à comprendre tes angles morts, à construire des relations authentiques et à transformer tes stratégies en actions concrètes.",
    jours: [
      { jour:1, phase:'moi', titre:"Ton système de pensée", conseil:"Tu ne vois pas le monde tel qu'il est — tu vois comment il pourrait être si tout était optimisé. Cette vision systémique est ta force mais elle peut aussi te rendre impatient(e) avec tout ce qui semble inefficace.", exercice:"Décris 1 système (au travail, chez toi) qui te frustre. Comment l'améliorer en 3 étapes ?" },
      { jour:2, phase:'moi', titre:"Compétence et identité", conseil:"Ta valeur personnelle est intimement liée à ton excellence. L'échec te touche donc plus profondément que tu ne l'admets. Mais ta valeur ne dépend pas de tes performances — c'est une distinction fondamentale à intégrer.", exercice:"Qu'est-ce qui reste vrai de toi si tu échoues demain sur quelque chose d'important ?" },
      { jour:3, phase:'moi', titre:"Ton mur émotionnel", conseil:"Tu traites les émotions comme des données à analyser. C'est efficace mais ça peut te couper des autres — et de toi-même. Les émotions non traitées s'accumulent et ressortent souvent au mauvais moment.", exercice:"Note 1 émotion ressentie cette semaine que tu as immédiatement rationalisée. C'était quoi vraiment ?" },
      { jour:4, phase:'moi', titre:"Ton impatience", conseil:"Tu comprends souvent plus vite que les autres et leur lenteur t'irrite. Mais ce que tu appelles 'lenteur' est parfois une attention à des détails que ta vision globale rate. Les deux perspectives sont nécessaires.", exercice:"Identifie 1 personne dont la 'lenteur' te frustre. Qu'est-ce qu'elle voit que tu pourrais rater ?" },
      { jour:5, phase:'moi', titre:"Ta recharge solitaire", conseil:"Tu as besoin de temps seul pour recharger, penser et reconstruire ton énergie. Ce n'est pas de l'arrogance ni de l'asociabilité — c'est ton mode de fonctionnement naturel et légitime.", exercice:"Planifie 2h cette semaine sans aucune obligation sociale. Utilise-les pour penser librement." },
      { jour:6, phase:'relations', titre:"Ton style de connexion", conseil:"Tu ne crées pas facilement des liens, mais ceux que tu crées sont durables et substantiels. La superficialité te fatigue plus qu'elle ne t'ennuie. Tu as besoin de sens même dans les relations.", exercice:"Identifie tes 2-3 vraies connexions. Qu'est-ce qui les a rendues possibles ?" },
      { jour:7, phase:'relations', titre:"Ce que tu cherches", conseil:"Tu cherches quelqu'un d'intellectuellement stimulant, d'autonome et qui te respecte sans chercher à te changer. Quelqu'un qui valorise la compétence et partage ton besoin d'espace.", exercice:"Quelles sont tes 3 qualités absolument non-négociables chez quelqu'un qui compte pour toi ?" },
      { jour:8, phase:'relations', titre:"Ton côté tranchant", conseil:"Ton directness et ton apparent manque d'empathie blessent parfois sans que tu le réalises. Tu ne cherches pas à blesser — tu cherches l'efficacité. Mais l'efficacité sans tact crée des dégâts dans les relations.", exercice:"Rappelle-toi 1 conversation où quelqu'un a semblé blessé sans raison évidente. Que s'est-il passé ?" },
      { jour:9, phase:'relations', titre:"Tes compatibilités", conseil:"Les ENTP, INFJ et ENFP te complètent souvent : ils pensent à ta vitesse mais t'apportent de la chaleur et de la flexibilité. Ils te challengent intellectuellement sans menacer ton indépendance.", exercice:"Pense à quelqu'un qui te tient tête intellectuellement. Est-ce un allié ou un adversaire ?" },
      { jour:10, phase:'relations', titre:"Comment tu aimes", conseil:"Tu aimes en optimisant la vie de l'autre, en planifiant l'avenir à deux et en étant absolument fiable quand ça compte. C'est un amour concret et profond — mais il mérite d'être aussi exprimé en mots parfois.", exercice:"Dis à quelqu'un qui compte : 'Tu peux compter sur moi.' Et prouve-le par un acte cette semaine." },
      { jour:11, phase:'projet', titre:"Ton environnement idéal", conseil:"Autonomie, efficacité et travail sur des problèmes complexes — c'est là que tu excelles. Le micromanagement, les réunions sans agenda et les processus bureaucratiques inutiles te paralysent lentement.", exercice:"Liste 3 conditions qui rendraient ton travail 40% plus efficace dès maintenant." },
      { jour:12, phase:'projet', titre:"Tes ambitions réelles", conseil:"Tu as probablement une vision à long terme que tu gardes pour toi par peur de ne pas l'accomplir ou de paraître présomptueux(se). Mais une ambition non déclarée reste un rêve. Déclarée, elle devient un projet.", exercice:"Écris ton objectif à 5 ans. Pas ce que tu devrais faire — ce que tu VEUX faire vraiment." },
      { jour:13, phase:'projet', titre:"La paralysie par le plan", conseil:"Tu planifies tellement bien que tu peux surpenser et ne jamais commencer. Le plan parfait existe rarement — le meilleur plan est celui qu'on exécute et qu'on ajuste en cours de route.", exercice:"Identifie 1 chose que tu 'prépares' depuis trop longtemps. Lance 1% cette semaine." },
      { jour:14, phase:'projet', titre:"Ta zone de génie", conseil:"Stratégie long terme, architecture de systèmes, résolution de problèmes complexes, leadership par la compétence — là où ta vision et ton exigence créent une valeur que peu peuvent reproduire.", exercice:"Quand as-tu été le/la plus efficace dans ta vie ? Quel contexte l'a permis ?" },
      { jour:15, phase:'projet', titre:"Ton prochain pas", conseil:"Tu vois le plan global avec une clarté rare. Maintenant exécute la première étape — même imparfaite. La stratégie la plus brillante ne vaut rien sans exécution. Le plan s'ajustera en cours de route.", exercice:"Choisis 1 objectif et identifie l'action minimale faisable avant demain soir." },
    ],
  },

  INTP: {
    typeCode: 'INTP', typeName: 'Le Logicien', emoji: '🔭',
    intro: "En tant qu'INTP, tu possèdes un esprit analytique d'une profondeur rare. Ce programme t'aide à transformer ta curiosité en action, à mieux vivre tes relations et à sortir des boucles de réflexion pour enfin créer.",
    jours: [
      { jour:1, phase:'moi', titre:"Ta curiosité comme moteur", conseil:"Tu es attiré(e) par la compréhension pour elle-même, pas pour son utilité immédiate. Ce besoin de comprendre est ta force centrale — et aussi ce qui peut te faire passer des heures sur des sujets 'inutiles' mais fascinants.", exercice:"Identifie le sujet sur lequel tu passes des heures sans t'en rendre compte. C'est un indice clé." },
      { jour:2, phase:'moi', titre:"Ton esprit non-linéaire", conseil:"Tu sautes d'une idée à l'autre en trouvant des connexions que les autres ratent. Ce n'est pas du désordre — c'est une forme de pensée créative qui génère des insights originaux en reliant des domaines éloignés.", exercice:"Note 3 idées 'folles' qui t'ont traversé cette semaine. L'une mérite peut-être d'être explorée." },
      { jour:3, phase:'moi', titre:"Ton rapport à l'émotion", conseil:"Tu tends à traiter les émotions comme des problèmes logiques à résoudre plutôt que comme des expériences à traverser. Ça te protège à court terme mais peut créer une déconnexion avec toi-même et les autres.", exercice:"Laisse-toi ressentir quelque chose sans l'analyser immédiatement. Juste 5 minutes aujourd'hui." },
      { jour:4, phase:'moi', titre:"L'exécution comme angle mort", conseil:"Tu génères des idées brillantes que tu ne finalises jamais. La finition te semble moins intéressante que le début. Mais un projet livré à 80% crée plus de valeur qu'une idée parfaite qui reste dans ta tête.", exercice:"Identifie 1 projet à 80% terminé. Finis-le cette semaine. Juste celui-là, rien d'autre." },
      { jour:5, phase:'moi', titre:"Ta solitude choisie", conseil:"Tu préfères souvent ta propre compagnie à celle de la plupart. C'est correct et légitime. Mais un isolement prolongé peut créer une dérive et un manque de feedback qui nuit à ta pensée.", exercice:"Planifie 1 interaction significative cette semaine — pas par obligation mais par choix réel." },
      { jour:6, phase:'relations', titre:"Connexion par les idées", conseil:"Tu te lies à travers les idées, pas les émotions. Les conversations superficielles t'ennuient rapidement. Une vraie conversation sur un sujet qui vous passionne tous les deux peut créer un lien fort instantanément.", exercice:"Identifie quelqu'un avec qui tu peux parler de n'importe quoi. Comment entretiens-tu ce lien ?" },
      { jour:7, phase:'relations', titre:"Ce que tu cherches", conseil:"Tu cherches quelqu'un qui stimule ton intellect et te laisse de l'espace. Quelqu'un qui ne prend pas ton besoin de solitude comme un rejet et qui peut tenir une conversation substantielle.", exercice:"Décris la dernière fois qu'une conversation t'a vraiment stimulé(e). Avec qui ? Pourquoi ?" },
      { jour:8, phase:'relations', titre:"Ton apparente froideur", conseil:"Les gens te perçoivent souvent comme distant(e) alors que tu es simplement absorbé(e) dans tes pensées. Ce décalage peut blesser des gens qui tiennent à toi sans que tu le réalises.", exercice:"Envoie aujourd'hui un message à quelqu'un de proche pour lui dire que tu penses à lui/elle." },
      { jour:9, phase:'relations', titre:"Tes compatibilités", conseil:"Les ENTJ, INFJ et ENFP t'apportent souvent ce qui te manque : structure, ancrage dans le réel et chaleur humaine. Ils te challengent sans te menacer et t'empêchent de rester trop longtemps dans ta tête.", exercice:"Pense à quelqu'un qui 'te sort de ta tête'. Quel rôle joue-t-il réellement dans ta vie ?" },
      { jour:10, phase:'relations', titre:"Comment tu aimes", conseil:"Tu aimes en partageant tes idées les plus secrètes, en construisant des systèmes qui facilitent la vie de l'autre et en étant là quand ça compte vraiment. C'est un amour discret mais profond.", exercice:"Montre à quelqu'un quelque chose qui te passionne vraiment. Laisse-toi être vu(e) pleinement." },
      { jour:11, phase:'projet', titre:"Ton environnement idéal", conseil:"Autonomie totale, problèmes complexes et absence de micromanagement — c'est là que ton intelligence se déploie. Les réunions inutiles et les tâches répétitives te consument sans rien te donner en retour.", exercice:"Identifie ce qui dans ton environnement actuel nuit le plus à ta concentration et ta réflexion." },
      { jour:12, phase:'projet', titre:"Tes idées non concrétisées", conseil:"Tu as souvent des idées brillantes que tu ne concrétises jamais. L'idée est plus excitante que l'exécution — mais l'idée seule ne change rien. Une idée imparfaite mais réalisée vaut 10 idées parfaites non lancées.", exercice:"Note ton idée la plus folle actuelle. Qu'est-ce qu'il faudrait pour la tester à petite échelle ?" },
      { jour:13, phase:'projet', titre:"La paralysie par l'analyse", conseil:"Tu repousses parce que tu sais que la solution n'est pas encore parfaite. Mais attendre la perfection est une forme de procrastination. Le projet imparfait livré enseigne infiniment plus que le projet parfait non lancé.", exercice:"Lance quelque chose cette semaine à 70% de ce que tu envisages. Observe ce qui se passe réellement." },
      { jour:14, phase:'projet', titre:"Ta zone de génie", conseil:"Recherche, analyse de systèmes, programmation, philosophie, sciences fondamentales — partout où la pensée profonde et originale est la valeur principale, tu es difficilement remplaçable par quiconque.", exercice:"Quand as-tu résolu un problème que personne d'autre n'avait vu ? Qu'as-tu fait différemment ?" },
      { jour:15, phase:'projet', titre:"Ton prochain pas", conseil:"L'INTP pense en boucles infinies. Coupe la boucle maintenant : une action concrète cette semaine sur ce qui compte le plus. Pas le plan parfait — l'action imparfaite qui te sort de la tête.", exercice:"Écris 1 action concrète. Mets une alarme pour demain. Fais-la avant 10h." },
    ],
  },

  ISFJ: {
    typeCode: 'ISFJ', typeName: 'Le Défenseur', emoji: '🛡️',
    intro: "En tant qu'ISFJ, tu es l'un des types les plus fiables et les plus attentionnés qui existe. Ce programme t'aide à prendre soin de toi autant que tu prends soin des autres, à poser des limites saines et à reconnaître ta propre valeur.",
    jours: [
      { jour:1, phase:'moi', titre:"Ton don naturel", conseil:"Tu donnes sans compter — temps, énergie, attention, soutien. C'est une qualité extraordinaire. Le problème : tu peux te vider complètement sans que personne s'en rende compte, parce que tu le fais en silence.", exercice:"Note ce que tu as donné cette semaine sans recevoir en retour. C'est quoi le bilan ?" },
      { jour:2, phase:'moi', titre:"Ton besoin de reconnaissance", conseil:"Tu travailles dur sans te plaindre, et tu attends souvent que les autres remarquent tes efforts. Cette attente silencieuse crée de la frustration et de la déception. Demander de la reconnaissance n'est pas de l'égoïsme.", exercice:"Dis à quelqu'un : 'J'ai fait X et j'aimerais que tu le reconnaisses.' C'est courageux, pas prétentieux." },
      { jour:3, phase:'moi', titre:"Ta difficulté à dire non", conseil:"Dire non te semble souvent égoïste ou blessant pour l'autre. Mais chaque 'oui' que tu donnes à contrecœur est un 'non' que tu te fais à toi-même. Ta générosité ne disparaît pas quand tu poses des limites.", exercice:"Dis non à une demande cette semaine. Sans excuse, sans longue explication. Juste : 'Je ne peux pas.'" },
      { jour:4, phase:'moi', titre:"Ton attachement au passé", conseil:"Tu es souvent gardien(ne) des traditions, des souvenirs et de la continuité. Ça apporte de la stabilité, mais ça peut aussi t'empêcher d'embrasser le changement quand il est nécessaire.", exercice:"Identifie 1 habitude ou croyance que tu gardes par tradition, pas par choix conscient." },
      { jour:5, phase:'moi', titre:"Comment tu te ressources", conseil:"Tu te ressources dans l'environnement familier, les rituels confortables et les relations proches. Les grands changements et les espaces inconnus t'épuisent. Il n'y a rien de mal à avoir besoin de stabilité.", exercice:"Identifie ton 'rituel de ressourcement' préféré. Est-ce que tu te l'accordes assez souvent ?" },
      { jour:6, phase:'relations', titre:"Ton style de soin", conseil:"Tu exprimes l'amour par des actes concrets — tu te souviens des petits détails, tu anticipes les besoins et tu es là dans les moments difficiles. C'est un langage d'amour puissant mais méconnu.", exercice:"Identifie quelqu'un qui t'aime à ta façon — par les actes. L'as-tu suffisamment reconnu(e) ?" },
      { jour:7, phase:'relations', titre:"Ce que tu cherches", conseil:"Tu cherches quelqu'un de fiable, qui valorise l'engagement et prend soin de toi comme tu prends soin des autres. La réciprocité n'est pas un luxe — c'est une nécessité pour ton équilibre.", exercice:"Dans tes relations proches, qui fait pour toi ce que tu fais pour les autres ? Qui ne le fait pas ?" },
      { jour:8, phase:'relations', titre:"Ton accumulation silencieuse", conseil:"Tu peux garder des frustrations des années sans les exprimer, puis ressentir un ressentiment profond envers quelqu'un qui ne sait même pas qu'il t'a blessé. Exprimer tôt protège la relation.", exercice:"Identifie 1 frustration gardée depuis longtemps. Comment la communiquer avec bienveillance ?" },
      { jour:9, phase:'relations', titre:"Tes compatibilités", conseil:"Les ESFJ, ISTJ et INFJ partagent souvent tes valeurs de loyauté et d'engagement. Les ESTP et ENFP t'apportent de la légèreté et te sortent de ta zone de confort de façon stimulante.", exercice:"Qui dans ta vie t'apporte de la légèreté et du nouveau ? Comment nourrir ce lien ?" },
      { jour:10, phase:'relations', titre:"Recevoir de l'amour", conseil:"Tu donnes facilement mais tu reçois difficillement. Accepter de l'aide, des compliments et du soin sans minimiser ou dévier — c'est une compétence que tu peux apprendre. Tu mérites aussi d'être soigné(e).", exercice:"La prochaine fois qu'on te complimente, dis simplement 'Merci.' Sans minimiser. Teste ça." },
      { jour:11, phase:'projet', titre:"Ton environnement idéal", conseil:"Tu travailles mieux dans un environnement stable, avec des rôles clairs et des relations de confiance. L'incertitude et le chaos constant t'épuisent. La prévisibilité n'est pas un manque d'ambition.", exercice:"Qu'est-ce qui dans ton environnement actuel te donne de la stabilité ? Qu'est-ce qui la menace ?" },
      { jour:12, phase:'projet', titre:"Tes ambitions discrètes", conseil:"Tu as souvent des ambitions que tu minimises parce qu'elles te semblent trop 'grandes' pour toi. La modestie est une qualité, mais se sous-estimer systématiquement est une forme d'injustice envers soi-même.", exercice:"Écris quelque chose que tu voudrais accomplir mais que tu n'oses pas dire. C'est déjà un début." },
      { jour:13, phase:'projet', titre:"Ta peur du changement", conseil:"Le changement représente l'inconnu, et l'inconnu est potentiellement dangereux. Tu préfères souvent la stabilité inconfortable à l'incertitude d'un mieux possible. Mais grandir nécessite parfois de quitter le confort.", exercice:"Identifie 1 changement que tu reports par peur. Qu'est le pire qui pourrait arriver réellement ?" },
      { jour:14, phase:'projet', titre:"Ta zone de génie", conseil:"Soin, organisation, fiabilité, mémoire des détails, loyauté — dans tous les environnements où ces qualités comptent (santé, éducation, administration, famille), tu crées une valeur irremplaçable.", exercice:"Dans quel domaine les gens te font-ils naturellement confiance ? C'est souvent là que tu excelles." },
      { jour:15, phase:'projet', titre:"Ton prochain pas", conseil:"Tu mets souvent les autres avant toi dans ta liste de priorités. Cette semaine, mets-toi en premier pour une chose. Une seule. Pas d'explication, pas de culpabilité — juste toi, en premier.", exercice:"Identifie quelque chose que tu as reporté parce que tu t'occupais des autres. Fais-le cette semaine." },
    ],
  },

  ISFP: {
    typeCode: 'ISFP', typeName: "L'Aventurier", emoji: '🎨',
    intro: "En tant qu'ISFP, tu vis dans le présent avec une authenticité que peu atteignent. Ce programme t'aide à mieux te connaître, à t'affirmer dans tes relations et à transformer ton art de vivre en véritable chemin.",
    jours: [
      { jour:1, phase:'moi', titre:"L'instant comme demeure", conseil:"Tu vis plus pleinement dans le présent que la plupart des gens. Le passé pèse peu, le futur te préoccupe peu. Cette présence au moment est un don rare qui permet de vivre des expériences intenses et authentiques.", exercice:"Note 3 moments cette semaine où tu t'es senti(e) pleinement vivant(e). Qu'avaient-ils en commun ?" },
      { jour:2, phase:'moi', titre:"Ton langage esthétique", conseil:"Tu penses et ressens souvent à travers les sens — couleurs, textures, sons, espaces. Ce n'est pas superficiel, c'est ta façon de traiter le monde. Tu vois et ressens ce que les autres passent devant sans voir.", exercice:"Crée quelque chose aujourd'hui — même petit. Dessin, photo, arrangement. Juste pour toi." },
      { jour:3, phase:'moi', titre:"Ton évitement du conflit", conseil:"Tu préfères fuir ou t'adapter plutôt qu'affronter. Ça maintient la paix à court terme mais crée de la frustration à long terme. Ce que tu gardes pour toi finit par peser plus lourd qu'une conversation difficile.", exercice:"Identifie 1 situation que tu évites depuis trop longtemps. Quel est le premier pas minuscule possible ?" },
      { jour:4, phase:'moi', titre:"Ton authenticité absolue", conseil:"Tu ne joues pas de rôle. Quand tu n'es pas à ta place ou qu'on te demande d'être quelqu'un d'autre, tu le ressens physiquement. Cette honnêteté à toi-même est l'une de tes plus grandes qualités.", exercice:"Identifie 1 aspect de ta vie actuelle qui ne te ressemble pas. Que ferais-tu si tu avais pleine liberté ?" },
      { jour:5, phase:'moi', titre:"Comment tu te ressources", conseil:"Tu te ressources dans la nature, la création, la solitude et les expériences sensorielles. Les longues discussions abstraites et les environnements artificiels te vident. Respecter ces besoins n'est pas de la faiblesse.", exercice:"Planifie cette semaine 1h dans un espace qui te ressource vraiment. Dehors, si possible." },
      { jour:6, phase:'relations', titre:"Ton affection discrète", conseil:"Tu aimes profondément mais tu l'exprimes rarement en mots — plutôt par ta présence, tes gestes et ta façon d'être là. Les gens peuvent ne pas réaliser à quel point tu tiens à eux.", exercice:"Dis à quelqu'un aujourd'hui ce que tu ressens pour lui/elle. En mots. Même maladroitement." },
      { jour:7, phase:'relations', titre:"Ce que tu cherches", conseil:"Tu cherches quelqu'un qui t'accepte tel(le) que tu es, sans te demander de te justifier ou de planifier l'avenir à 10 ans. Quelqu'un qui partage ton goût pour les expériences authentiques et le présent.", exercice:"Dans tes relations actuelles, qui t'accepte le plus pleinement sans vouloir te changer ?" },
      { jour:8, phase:'relations', titre:"Ton absorption des conflits", conseil:"Tu préfères t'adapter plutôt que de provoquer un conflit. Mais t'adapter indéfiniment aux besoins des autres au détriment des tiens crée un ressentiment silencieux qui finit par tout empoisonner.", exercice:"Pense à 1 besoin que tu n'exprimes pas pour éviter le conflit. Comment le communiquer doucement ?" },
      { jour:9, phase:'relations', titre:"Tes compatibilités", conseil:"Les ESFJ, ENFJ et INFJ apportent souvent la structure et la profondeur qui te manquent parfois. Les ESTP et ENFP partagent ton goût pour l'expérience et le présent, créant des liens naturellement joyeux.", exercice:"Pense à quelqu'un qui te donne à la fois de la liberté et de l'ancrage. Quel rôle joue-t-il ?" },
      { jour:10, phase:'relations', titre:"Comment tu aimes", conseil:"Tu aimes par ta présence totale, tes gestes doux et ta capacité à être là sans jugement. Tu adaptes ton énergie à l'autre instinctivement. C'est un don rare qui mérite d'être reconnu.", exercice:"Reconnais la façon dont quelqu'un t'aime, même si c'est différente de comment tu t'y attendais." },
      { jour:11, phase:'projet', titre:"Ton environnement idéal", conseil:"Tu travailles mieux avec autonomie, dans un cadre qui laisse place à la créativité et où l'authenticité est valorisée. Les environnements rigides et les tâches purement mécaniques te vident de ton énergie.", exercice:"Identifie le projet ou travail dans lequel tu t'es senti(e) le/la plus librement toi-même." },
      { jour:12, phase:'projet', titre:"Tes projets d'un jour", conseil:"Tu démarres beaucoup de choses avec enthousiasme et tu en finis moins. Ce n'est pas de la paresse — c'est que l'initiation t'attire plus que la finalisation. Identifier ça est la première étape.", exercice:"Choisis 1 projet commencé et non terminé. Engage-toi à le finir avant vendredi. Un seul." },
      { jour:13, phase:'projet', titre:"Ta résistance à la planification", conseil:"Planifier l'avenir te semble parfois trahir ta nature présente. Mais quelques ancrages de long terme peuvent libérer — pas contraindre — ta liberté quotidienne. Un cap, pas des chaînes.", exercice:"Décris à quoi ressemble ta vie dans 1 an si tout se passe bien. Juste 3 lignes." },
      { jour:14, phase:'projet', titre:"Ta zone de génie", conseil:"Art, design, soins, artisanat, travail social — partout où l'authenticité humaine et la sensibilité sont la valeur principale, tu crées quelque chose que les autres ne peuvent pas reproduire mécaniquement.", exercice:"Dans quel domaine les gens te disent-ils 'tu as un truc particulier' ? C'est souvent ta zone de génie." },
      { jour:15, phase:'projet', titre:"Ton prochain pas", conseil:"L'ISFP vit si bien dans le présent qu'il peut oublier de construire. Cette semaine, fais 1 chose qui te sert aussi dans 6 mois. Un seul investissement dans ton futur, choisi librement.", exercice:"Identifie 1 action cette semaine qui à la fois te plaît maintenant ET te sert dans 6 mois." },
    ],
  },

  ISTJ: {
    typeCode: 'ISTJ', typeName: 'Le Logisticien', emoji: '📋',
    intro: "En tant qu'ISTJ, tu es l'une des personnes les plus fiables et les plus organisées qui existe. Ce programme t'aide à comprendre ta relation aux émotions, à enrichir tes liens et à embrasser le changement sans trahir ta nature.",
    jours: [
      { jour:1, phase:'moi', titre:"Ta fiabilité comme force", conseil:"Tu fais ce que tu dis et tu dis ce que tu fais. Dans un monde de promesses non tenues, c'est une qualité extraordinairement rare. Mais cette même fiabilité peut devenir une prison si elle t'empêche de te permettre d'être faillible.", exercice:"Identifie 1 domaine où tu t'es imposé(e) une norme si haute qu'elle te pèse. Est-ce vraiment nécessaire ?" },
      { jour:2, phase:'moi', titre:"Ton rapport aux règles", conseil:"Tu respectes les règles parce qu'elles ont fait leurs preuves, pas par peur. Cette confiance dans les systèmes éprouvés est une force — mais elle peut aussi t'empêcher de voir quand une règle est devenue obsolète.", exercice:"Identifie 1 règle ou habitude que tu suis depuis longtemps. La choisis-tu encore consciemment ?" },
      { jour:3, phase:'moi', titre:"Tes émotions sous la surface", conseil:"Tu exprimes rarement tes émotions, ce qui ne veut pas dire que tu ne les ressens pas. Elles existent — elles s'expriment juste différemment, souvent à travers les actes plutôt que les mots.", exercice:"Identifie 1 émotion que tu as ressentie cette semaine et que tu n'as pas exprimée. C'était quoi ?" },
      { jour:4, phase:'moi', titre:"Ta résistance au changement", conseil:"Le changement représente l'incertitude, et l'incertitude est potentiellement inefficace. Mais certains changements améliorent les systèmes. Distinguer le changement utile du changement pour le changement est une compétence.", exercice:"Pense à 1 changement récent qui s'est révélé positif malgré ta résistance initiale. Qu'as-tu appris ?" },
      { jour:5, phase:'moi', titre:"Comment tu te ressources", conseil:"Tu te ressources dans la solitude structurée, les routines confortables et les tâches concrètes accomplie. Les environnements chaotiques et imprévisibles t'épuisent. C'est une information, pas une limitation.", exercice:"Identifie ta routine de ressourcement la plus efficace. Est-ce que tu te l'accordes assez souvent ?" },
      { jour:6, phase:'relations', titre:"Ton style de soin", conseil:"Tu montres que tu tiens à quelqu'un en étant là, en tenant tes engagements et en faisant des choses concrètes pour lui/elle. L'amour en actes. Certains le voient, d'autres attendent des mots qu'ils n'entendront pas.", exercice:"Y a-t-il quelqu'un dans ta vie qui a besoin d'entendre ta gratitude en mots, pas juste en actes ?" },
      { jour:7, phase:'relations', titre:"Ce que tu cherches", conseil:"Tu cherches quelqu'un de fiable, honnête et engagé. Quelqu'un dont les actes correspondent aux paroles. La cohérence et la loyauté sont pour toi des qualités non-négociables.", exercice:"Dans tes relations actuelles, qui respecte le plus ta fiabilité en étant fiable à son tour ?" },
      { jour:8, phase:'relations', titre:"Tes attentes non dites", conseil:"Tu peux avoir des attentes élevées envers les autres sans les avoir explicitement formulées. Puis tu es déçu(e) quand ils ne les remplissent pas, même si tu ne les leur as jamais communiquées.", exercice:"Identifie 1 attente que tu as envers quelqu'un que tu n'as jamais exprimée. Comment la communiquer ?" },
      { jour:9, phase:'relations', titre:"Tes compatibilités", conseil:"Les ESFJ, ISTJ et ISFJ partagent tes valeurs de fiabilité et d'engagement. Les ESTP et ENFP t'apportent de la spontanéité et une façon différente de voir le monde qui peut être enrichissante.", exercice:"Pense à quelqu'un très différent de toi avec qui tu t'entends bien. Qu'est-ce que ça t'apporte ?" },
      { jour:10, phase:'relations', titre:"Comment tu aimes", conseil:"Tu aimes en étant absolument fiable, en te souvenant de ce qui compte pour l'autre et en construisant quelque chose de durable ensemble. C'est un amour solide et profond.", exercice:"Montre à quelqu'un qui compte que tu te souviens de quelque chose d'important pour lui/elle." },
      { jour:11, phase:'projet', titre:"Ton environnement idéal", conseil:"Structure claire, rôles définis, processus éprouvés — c'est là que tu excelles. L'ambiguïté permanente et le chaos organisationnel te font perdre de l'efficacité et de l'énergie inutilement.", exercice:"Liste 3 conditions qui te permettent de travailler à ton meilleur niveau. Lesquelles manquent ?" },
      { jour:12, phase:'projet', titre:"Tes ambitions concrètes", conseil:"Tu as des ambitions, mais elles sont souvent concrètes et pragmatiques plutôt que spectaculaires. C'est une force — les grandes choses sont souvent accomplies par des gens qui font bien les choses simples de façon constante.", exercice:"Définis ton objectif principal actuel. Est-il clairement défini avec un délai et des étapes ?" },
      { jour:13, phase:'projet', titre:"Ton rapport au risque", conseil:"Tu préfères la certitude au risque. C'est souvent sage. Mais parfois, la sécurité absolue est une illusion qui t'empêche de saisir des opportunités qui méritent un peu d'incertitude.", exercice:"Identifie 1 opportunité que tu as laissée passer par prudence excessive. Qu'aurais-tu fait différemment ?" },
      { jour:14, phase:'projet', titre:"Ta zone de génie", conseil:"Organisation, gestion de projet, comptabilité, droit, ingénierie, logistique — partout où la rigueur, la fiabilité et l'attention aux détails créent une valeur irremplaçable, tu es dans ta zone.", exercice:"Dans quel domaine les gens te font-ils confiance instinctivement ? C'est souvent ta zone de valeur." },
      { jour:15, phase:'projet', titre:"Ton prochain pas", conseil:"Tu sais planifier. Tu sais exécuter. Cette semaine, applique ces forces à quelque chose qui compte pour TOI — pas juste pour les obligations. Un objectif personnel, pas juste professionnel.", exercice:"Identifie 1 objectif personnel (pas professionnel). Fais 1 pas concret vers lui cette semaine." },
    ],
  },

  ISTP: {
    typeCode: 'ISTP', typeName: 'Le Virtuose', emoji: '🔧',
    intro: "En tant qu'ISTP, tu combines une maîtrise pratique rare avec une indépendance absolue. Ce programme t'aide à mieux naviguer tes relations, à comprendre tes besoins émotionnels et à canaliser ton énergie vers ce qui compte.",
    jours: [
      { jour:1, phase:'moi', titre:"Ta maîtrise pratique", conseil:"Tu apprends en faisant. Tu comprends comment les choses fonctionnent en les démontant et les reconstruisant. Cette intelligence pratique est une compétence que beaucoup admirent sans vraiment la posséder.", exercice:"Identifie 1 compétence pratique que tu as et que tu sous-estimes. Comment pourrait-elle créer de la valeur ?" },
      { jour:2, phase:'moi', titre:"Ton besoin d'indépendance", conseil:"La liberté n'est pas un luxe pour toi — c'est une nécessité. Te sentir contrôlé(e) ou micromanagé(e) génère une résistance immédiate et souvent physique. Comprendre ça t'aide à choisir les bons environnements.", exercice:"Identifie les 2 dernières fois où tu t'es senti(e) contraint(e). Qu'est-ce qui déclenchait cette réaction ?" },
      { jour:3, phase:'moi', titre:"Ton rapport à l'émotion", conseil:"Tu traites les émotions avec logique plutôt que sentiment. Ce n'est pas de la froideur — c'est ton mode de traitement. Mais certaines situations demandent une réponse émotionnelle que la logique seule ne peut pas fournir.", exercice:"Note 1 situation récente où une réponse émotionnelle aurait été plus efficace que ta réponse logique." },
      { jour:4, phase:'moi', titre:"Ton ennui comme signal", conseil:"L'ennui est pour toi un signal fort : quelque chose ne fonctionne pas et doit changer. Écouter ce signal te permet d'identifier rapidement ce qui ne te convient plus avant que ça devienne une frustration chronique.", exercice:"Qu'est-ce qui t'ennuie le plus en ce moment ? Qu'est-ce que ça signale sur tes besoins réels ?" },
      { jour:5, phase:'moi', titre:"Comment tu te ressources", conseil:"Tu te ressources dans l'action, le mouvement et la résolution de problèmes concrets. Les longues discussions abstraites et les environnements très sociaux t'épuisent rapidement. Respecter ce rythme est essentiel.", exercice:"Identifie ton activité de ressourcement préférée. Est-ce que tu te l'accordes assez souvent ?" },
      { jour:6, phase:'relations', titre:"Ton style distant", conseil:"Tu peux sembler distant(e) alors que tu observes simplement. Les gens peuvent se sentir rejetés par ton silence sans comprendre que c'est ton mode naturel d'engagement avec le monde.", exercice:"La prochaine fois que tu es silencieux(se) avec quelqu'un, dis-lui : 'Je réfléchis, c'est tout.' Simple." },
      { jour:7, phase:'relations', titre:"Ce que tu cherches", conseil:"Tu cherches quelqu'un qui respecte ton espace et n'essaie pas de te changer. Quelqu'un d'autonome qui comprend que ton silence n'est pas un rejet et ton indépendance n'est pas du désintérêt.", exercice:"Dans ta relation principale, qu'est-ce qui respecte ton espace ? Qu'est-ce qui l'envahit ?" },
      { jour:8, phase:'relations', titre:"Tes conflits évités", conseil:"Tu n'aimes pas les conflits émotionnels. Tu préfères partir ou te fermer. Mais éviter systématiquement les conflits crée une distance et un ressentiment plus difficile à gérer que la conversation initiale.", exercice:"Identifie 1 conflit que tu as évité. Comment aurait pu se passer une vraie conversation courte ?" },
      { jour:9, phase:'relations', titre:"Tes compatibilités", conseil:"Les ESTJ, ENTJ et ESTP partagent ton pragmatisme. Les INFJ et ENFP t'apportent de la profondeur émotionnelle qui peut t'enrichir si tu leur laisses la place de le faire sans te sentir envahi(e).", exercice:"Pense à quelqu'un qui t'apporte quelque chose que tu n'as pas naturellement. Comment valoriser ça ?" },
      { jour:10, phase:'relations', titre:"Comment tu aimes", conseil:"Tu aimes en étant là quand ça compte, en résolvant les problèmes pratiques de l'autre et en partageant tes compétences. C'est un amour concret qui parle d'actions, pas de grandes déclarations.", exercice:"Fais quelque chose de concret cette semaine pour quelqu'un qui compte — résous un de leurs problèmes." },
      { jour:11, phase:'projet', titre:"Ton environnement idéal", conseil:"Autonomie, problèmes concrets à résoudre, liberté de trouver ta propre méthode — c'est là que tu excelles. Les procédures rigides et les réunions inutiles te consument sans rien produire.", exercice:"Identifie 3 conditions dans lesquelles tu es le/la plus efficace. Lesquelles peux-tu créer maintenant ?" },
      { jour:12, phase:'projet', titre:"Tes projets abandonnés", conseil:"Tu démarres des projets avec une énergie intense et tu peux t'en désintéresser une fois le défi résolu. Ce n'est pas de l'inconstance — c'est que tu es motivé(e) par le problème, pas par la gestion quotidienne.", exercice:"Identifie 1 projet abandonné. Était-ce un abandon ou une complétion du défi initial ?" },
      { jour:13, phase:'projet', titre:"Ton horizon court terme", conseil:"Tu excelles dans le présent et le court terme. Le long terme te semble moins réel. Mais quelques repères à 1-2 ans peuvent libérer — pas contraindre — ton énergie quotidienne.", exercice:"Décris à quoi ressemble ta situation idéale dans 18 mois. Juste les grandes lignes." },
      { jour:14, phase:'projet', titre:"Ta zone de génie", conseil:"Mécanique, ingénierie, programmation, chirurgie, sport, artisanat de précision — partout où la maîtrise technique et la résolution de problèmes concrets sont la valeur principale, tu es dans ta zone.", exercice:"Dans quel domaine pratique te sens-tu le/la plus compétent(e) ? Comment approfondir encore ?" },
      { jour:15, phase:'projet', titre:"Ton prochain pas", conseil:"L'ISTP est capable d'action immédiate et efficace. Cette semaine, applique cette capacité à quelque chose qui compte vraiment pour ton propre développement — pas juste pour résoudre le problème d'un autre.", exercice:"Choisis 1 défi personnel. Commence à le résoudre aujourd'hui. Comme tu résoudrais n'importe quel problème." },
    ],
  },

  ENFJ: {
    typeCode: 'ENFJ', typeName: 'Le Protagoniste', emoji: '🌟',
    intro: "En tant qu'ENFJ, tu as un don naturel pour inspirer et élever les autres. Ce programme t'aide à te nourrir autant que tu nourris les autres, à poser tes propres besoins et à channeliser ton charisme au service de ce qui compte vraiment.",
    jours: [
      { jour:1, phase:'moi', titre:"Ton don du leadership", conseil:"Tu inspires les gens sans effort apparent. Tu vois le potentiel des autres avant qu'ils le voient eux-mêmes. Ce don est puissant — et épuisant si tu l'exerces sans jamais te ressourcer.", exercice:"Identifie la dernière fois que tu as inspiré quelqu'un. Comment ça t'a-t-il affecté(e) toi ?" },
      { jour:2, phase:'moi', titre:"L'oubli de soi", conseil:"Tu mets si souvent les besoins des autres avant les tiens que tu peux oublier ce que tu veux vraiment. Cette générosité admirable peut devenir une forme d'auto-négation si elle n'est pas équilibrée.", exercice:"Qu'est-ce que TU veux vraiment en ce moment — pour toi, pas pour les autres ?" },
      { jour:3, phase:'moi', titre:"Ton besoin d'approbation", conseil:"Même si tu sembles confiant(e), tu peux être profondément affecté(e) par la critique ou le rejet. Ta valeur ne dépend pas du regard des autres — c'est une distinction fondamentale à intégrer vraiment.", exercice:"Rappelle-toi 1 critique reçue récemment. Comment l'as-tu traitée ? Était-ce proportionnel ?" },
      { jour:4, phase:'moi', titre:"Ta charge émotionnelle", conseil:"Tu absorbes les émotions de tout le groupe. Dans une pièce tendue, tu ressens tout et tu travailles inconsciemment à rétablir l'harmonie. C'est épuisant sans que tu t'en rendes toujours compte.", exercice:"Après ta prochaine réunion ou rassemblement, évalue ton niveau d'énergie avant et après." },
      { jour:5, phase:'moi', titre:"Comment tu te ressources", conseil:"Tu as besoin de moments seul(e) plus que tu ne le crois, même si tu es extraverti(e). Ces moments sont nécessaires pour traiter tout ce que tu as absorbé et te reconnecter à tes propres besoins.", exercice:"Planifie 30 minutes cette semaine où tu es seul(e) sans aucune responsabilité envers qui que ce soit." },
      { jour:6, phase:'relations', titre:"Ton empathie comme atout", conseil:"Tu comprends ce que les gens ressentent avant qu'ils le formulent. C'est un super-pouvoir dans les relations. Mais tu peux aussi t'épuiser à porter les émotions des autres comme si elles étaient les tiennes.", exercice:"Cette semaine, avant d'absorber l'émotion de quelqu'un, demande-toi : 'Est-ce mon rôle de porter ça ?'" },
      { jour:7, phase:'relations', titre:"Ce que tu cherches", conseil:"Tu cherches quelqu'un qui prend soin de toi autant que tu prends soin des autres — quelqu'un qui remarque quand tu as besoin d'aide sans que tu aies à le demander. La réciprocité est ta blessure cachée.", exercice:"Dans tes relations proches, qui s'assure que TU vas bien ? Pas l'inverse." },
      { jour:8, phase:'relations', titre:"Ta peur du conflit", conseil:"Tu travailles naturellement à maintenir l'harmonie, parfois au détriment de ta propre vérité. Dire quelque chose qui pourrait blesser même quand c'est nécessaire est une compétence que tu peux développer.", exercice:"Pense à 1 vérité que tu retenais pour préserver l'harmonie. Comment la dire avec bienveillance ?" },
      { jour:9, phase:'relations', titre:"Tes compatibilités", conseil:"Les INFP, INTJ et ENFP te complètent souvent — ils apportent profondeur individuelle et vision. Les ISTJ et ESTJ t'ancrent dans le concret quand tu as tendance à t'envoler dans l'idéal.", exercice:"Qui dans ta vie t'ancre dans le réel quand tu t'emballe ? Comment valoriser ce rôle ?" },
      { jour:10, phase:'relations', titre:"Comment tu aimes", conseil:"Tu aimes en inspirant, en poussant l'autre à devenir meilleur et en étant là avec une intensité totale. Mais l'autre doit aussi choisir sa propre croissance — tu ne peux pas grandir à sa place.", exercice:"Y a-t-il quelqu'un que tu tries de 'sauver' ou d'élever sans qu'il te le demande vraiment ?" },
      { jour:11, phase:'projet', titre:"Ton environnement idéal", conseil:"Tu excelles dans les rôles de leadership, enseignement et animation où tu peux inspirer un groupe vers un but commun. Les environnements sans vision ni impact humain direct te laissent vide.", exercice:"Dans quel rôle te sens-tu le/la plus vivant(e) professionnellement ? Qu'est-ce que ça révèle ?" },
      { jour:12, phase:'projet', titre:"Tes ambitions pour l'humanité", conseil:"Tes ambitions sont souvent liées à l'impact collectif. Tu veux changer des choses, élever les gens, créer quelque chose qui dure. C'est une belle force — et une source de pression énorme si elle n'est pas canalisée.", exercice:"Quel est l'impact que tu veux avoir dans 5 ans ? Sois spécifique." },
      { jour:13, phase:'projet', titre:"Ton perfectionnisme social", conseil:"Tu peux te mettre une pression énorme pour être parfait(e) dans ton rôle de leader, d'ami(e) et de soutien. Cette perfection n'est pas atteignable — et l'essayer t'épuise inutilement.", exercice:"Identifie 1 standard que tu t'imposes envers toi-même que tu n'imposerais jamais à quelqu'un d'autre." },
      { jour:14, phase:'projet', titre:"Ta zone de génie", conseil:"Leadership transformationnel, enseignement, coaching, conseil, politique, diplomatie — partout où inspirer et mobiliser les gens vers un but commun est la compétence clé, tu es dans ta zone naturelle.", exercice:"Rappelle-toi 1 moment où tu as vraiment changé quelque chose pour quelqu'un. Comment ça s'est passé ?" },
      { jour:15, phase:'projet', titre:"Ton prochain pas", conseil:"Tu inspires tellement les autres que tu oublies parfois de t'inspirer toi-même. Cette semaine, quel est ton propre prochain pas — pas celui de ton équipe, pas celui de tes proches, le tien ?", exercice:"Identifie 1 objectif personnel que tu remets à plus tard parce que tu t'occupes des autres. Avance dessus." },
    ],
  },

  ENFP: {
    typeCode: 'ENFP', typeName: 'Le Champion', emoji: '🦋',
    intro: "En tant qu'ENFP, tu es une source d'énergie et d'inspiration naturelle. Ce programme t'aide à canaliser ton enthousiasme, à finir ce que tu commences et à approfondir tes relations au-delà de l'enthousiasme initial.",
    jours: [
      { jour:1, phase:'moi', titre:"Ton énergie contagieuse", conseil:"Tu entres dans une pièce et tu changes son atmosphère. Ton enthousiasme est sincère et communicatif. C'est un don rare — mais il peut aussi t'épuiser si tu te sens responsable de l'énergie de tout le monde.", exercice:"Identifie les situations où tu 'joues' l'enthousiaste alors que tu n'en as pas vraiment envie." },
      { jour:2, phase:'moi', titre:"Ton besoin de nouveauté", conseil:"Le nouveau te vivifie. L'ancien te pèse rapidement. C'est ce qui te rend créatif(ve) et innovant(e) — mais c'est aussi ce qui fait que tu laisses des projets à 80% pour commencer le suivant.", exercice:"Liste tes 3 derniers projets abandonnés. Qu'avaient-ils en commun ? Qu'est-ce qui a déclenché l'arrêt ?" },
      { jour:3, phase:'moi', titre:"Ton monde de possibilités", conseil:"Tu vois les possibilités partout — dans chaque personne, chaque situation, chaque idée. C'est exaltant. Mais trop de possibilités sans choix crée une paralysie douce et une impression de passer à côté de tout.", exercice:"Identifie 1 possibilité concrète que tu veux VRAIMENT concrétiser. Juste une." },
      { jour:4, phase:'moi', titre:"Ta sensibilité masquée", conseil:"Sous ton extraversion joyeuse se cache une sensibilité profonde que peu voient. Tu peux être blessé(e) bien plus facilement que tu ne le laisses paraître. Et tu guéris parfois plus lentement aussi.", exercice:"Note 1 chose qui t'a blessé(e) récemment que tu n'as pas exprimée. À quoi ressemblerait l'exprimer ?" },
      { jour:5, phase:'moi', titre:"Comment tu te ressources", conseil:"Tu te ressources dans les conversations profondes, les nouvelles expériences et les projets créatifs. Les routines répétitives et les environnements sans stimulation t'épuisent même si tu dépenses peu d'énergie.", exercice:"Identifie l'activité qui te recharge le mieux. Est-ce que tu en fais assez ?" },
      { jour:6, phase:'relations', titre:"Ton intensité relationnelle", conseil:"Tu t'engages vite et fort dans les nouvelles relations. Cette chaleur est attirante. Mais tu peux idéaliser l'autre dans les premières semaines et être déçu(e) quand la réalité nuance l'enthousiasme initial.", exercice:"Dans ta dernière relation forte (amour ou amitié), qu'as-tu projeté qui n'était pas là au début ?" },
      { jour:7, phase:'relations', titre:"Ce que tu cherches", conseil:"Tu cherches quelqu'un qui partage ton enthousiasme pour les idées et les expériences — mais qui peut aussi t'ancrer dans le réel quand tu t'envoles. Quelqu'un qui tient le cap quand tu changes de direction.", exercice:"Dans tes relations actuelles, qui t'ancre sans t'étouffer ? Comment nourrir ce lien ?" },
      { jour:8, phase:'relations', titre:"Ton évitement de l'ennui", conseil:"Quand une relation devient 'confortable', tu peux inconsciemment la saboter ou chercher de la nouveauté ailleurs. L'ennui n'est pas toujours un signal que quelque chose doit changer — parfois c'est la profondeur qui commence.", exercice:"Identifie 1 relation 'confortable' que tu tends à négliger. Qu'est-ce qu'elle t'apporte que la nouveauté n'offre pas ?" },
      { jour:9, phase:'relations', titre:"Tes compatibilités", conseil:"Les INTJ, INFJ et ENTJ te complètent souvent — ils apportent structure, profondeur et vision à long terme. Ils t'ancrent sans t'étouffer si la relation est bien équilibrée.", exercice:"Pense à quelqu'un qui 'te cadre' naturellement. Comment s'assurer que ce cadre reste utile et pas contraignant ?" },
      { jour:10, phase:'relations', titre:"Comment tu aimes", conseil:"Tu aimes avec une intensité et une créativité rares — surprises, explorations, conversations de 3h du matin, projets partagés. Tu as besoin d'un(e) partenaire qui peut courir à ton rythme.", exercice:"Fais quelque chose de créatif et inattendu pour quelqu'un qui compte cette semaine." },
      { jour:11, phase:'projet', titre:"Ton environnement idéal", conseil:"Liberté, créativité, variété et impact humain visible — c'est ton carburant. Les environnements rigides et répétitifs te consument. Tu as besoin de voir que ce que tu fais change quelque chose.", exercice:"Décris ton environnement de travail idéal en 5 mots. Qu'est-ce qui manque dans ta situation actuelle ?" },
      { jour:12, phase:'projet', titre:"Ta guerre à la finition", conseil:"Commencer est ton point fort. Finir est ton défi. La finition demande de la persévérance sur quelque chose qui n'est plus nouveau — et c'est là que ton énergie naturelle faiblit.", exercice:"Identifie 1 projet à 70%+ terminé. Engage-toi à le finir avant la fin de la semaine. Un seul." },
      { jour:13, phase:'projet', titre:"Tes grandes ambitions", conseil:"Tu as des ambitions à la mesure de ton enthousiasme — souvent très grandes. L'enjeu est de choisir 1-2 directions et de les tenir assez longtemps pour créer une vraie traction.", exercice:"Si tu ne pouvais réaliser qu'UN seul projet dans les 12 prochains mois, ce serait lequel ?" },
      { jour:14, phase:'projet', titre:"Ta zone de génie", conseil:"Marketing, entrepreneuriat, conseil, animation, coaching, art, enseignement — partout où inspirer, connecter et créer du mouvement sont la valeur principale, tu es naturellement brillant(e).", exercice:"Rappelle-toi un projet qui t'a pleinement absorbé(e). Qu'est-ce qui le rendait si engageant ?" },
      { jour:15, phase:'projet', titre:"Ton prochain pas", conseil:"L'ENFP a mille idées et peu de finitions. Cette semaine, une seule règle : finir quelque chose avant d'en commencer un nouveau. Une seule finition peut changer ta relation à l'action.", exercice:"Choisis 1 chose à finir avant vendredi. Finis-la. Célèbre-la." },
    ],
  },

  ENTJ: {
    typeCode: 'ENTJ', typeName: 'Le Commandant', emoji: '⚔️',
    intro: "En tant qu'ENTJ, tu combines vision stratégique et capacité d'exécution de façon rare. Ce programme t'aide à comprendre tes angles morts relationnels, à mieux nourrir tes connexions et à diriger sans te perdre.",
    jours: [
      { jour:1, phase:'moi', titre:"Ton leadership naturel", conseil:"Tu prends naturellement les rênes sans te demander si tu dois le faire. C'est un don — et une source de conflits quand les autres n'ont pas demandé à être dirigés. L'efficacité sans invitation crée de la résistance.", exercice:"Identifie 1 situation récente où tu as pris le leadership sans qu'on te le demande. Quel a été l'effet ?" },
      { jour:2, phase:'moi', titre:"Ton rapport à l'échec", conseil:"L'échec te touche plus profondément que tu ne l'admets, parce que ton identité est liée à ta capacité à réussir. Mais l'échec est de l'information — pas une sentence. Les meilleurs stratèges apprennent vite.", exercice:"Rappelle-toi 1 échec qui t'a marqué(e). Quelle est la leçon que tu en as tirée vraiment ?" },
      { jour:3, phase:'moi', titre:"Ton impatience", conseil:"Tu vois le chemin le plus court entre A et B avec clarté. L'inefficacité t'irrite profondément. Mais ce que tu appelles inefficacité est parfois le temps nécessaire pour que les autres comprennent et adhèrent.", exercice:"Identifie 1 personne dont le rythme te frustre. Qu'est-ce qu'elle voit ou ressent que tu ignores ?" },
      { jour:4, phase:'moi', titre:"Ta vulnérabilité cachée", conseil:"Sous ta confiance visible se cachent parfois des doutes que tu ne montres jamais. Cette invulnérabilité affichée peut isoler — personne n'ose être vulnérable avec quelqu'un qui semble n'avoir aucun doute.", exercice:"Partage 1 doute ou incertitude avec quelqu'un de proche. C'est plus fort que ça n'y paraît." },
      { jour:5, phase:'moi', titre:"Comment tu te ressources", conseil:"Tu te ressources dans l'action, la résolution de problèmes et les défis stimulants. L'inaction prolongée te pèse. Mais sans moments de récupération réelle, ton efficacité baisse sans que tu le réalises.", exercice:"Identifie ton dernier vrai moment de repos. Était-ce assez récent ?" },
      { jour:6, phase:'relations', titre:"Ton style direct", conseil:"Ta communication directe est efficace mais peut blesser sans que tu t'en rendes compte. Ce que tu appelles 'feedback' peut être vécu comme une attaque. Le delivery importe autant que le message.", exercice:"Rappelle-toi une conversation où quelqu'un a semblé blessé. Comment aurais-tu pu livrer le même message autrement ?" },
      { jour:7, phase:'relations', titre:"Ce que tu cherches", conseil:"Tu cherches quelqu'un d'ambitieux et capable qui ne te demande pas de ralentir. Quelqu'un qui te tient tête intellectuellement et qui peut tenir le rythme sans se perdre.", exercice:"Quelles sont les 3 qualités non-négociables chez quelqu'un qui compte pour toi ?" },
      { jour:8, phase:'relations', titre:"Ton besoin de contrôle", conseil:"Tu peux avoir tendance à optimiser et diriger même dans tes relations proches. Mais l'amour et l'amitié ne sont pas des projets à gérer. Lâcher prise dans les relations crée une proximité que le contrôle empêche.", exercice:"Identifie 1 relation où tu contrôles trop. Comment lâcher 1 chose concrète cette semaine ?" },
      { jour:9, phase:'relations', titre:"Tes compatibilités", conseil:"Les INTJ, INTP et ENFP te complètent souvent — vision analytique et créativité qui enrichissent ton pragmatisme. Les INFJ apportent une profondeur émotionnelle qui peut te surprendre et t'enrichir.", exercice:"Pense à quelqu'un qui te surprend régulièrement. Qu'est-ce que tu apprends de lui/elle ?" },
      { jour:10, phase:'relations', titre:"Comment tu aimes", conseil:"Tu aimes en construisant, en planifiant l'avenir et en poussant l'autre à devenir meilleur. Mais l'autre a parfois juste besoin de se sentir accepté(e), pas optimisé(e). Les deux sont nécessaires.", exercice:"Fais quelque chose juste pour faire plaisir à quelqu'un, sans agenda ni optimisation. Juste pour lui/elle." },
      { jour:11, phase:'projet', titre:"Ton environnement idéal", conseil:"Vision claire, équipe capable et liberté d'exécution — c'est là que tu crées ton impact maximal. Les environnements bureaucratiques et les équipes non-engagées te frustrent profondément.", exercice:"Dans ton environnement actuel, qu'est-ce qui te freine le plus dans ton efficacité ?" },
      { jour:12, phase:'projet', titre:"Tes ambitions à long terme", conseil:"Tu as probablement une vision à 10 ans que peu réaliseraient. C'est ta force. L'enjeu est de ne pas sacrifier le présent — les relations, la santé, le bonheur — sur l'autel de cette ambition.", exercice:"Dans 10 ans, qu'est-ce que tu veux avoir accompli ? Et à quel prix es-tu prêt(e) à le faire ?" },
      { jour:13, phase:'projet', titre:"Ton rapport aux autres dans le projet", conseil:"Tu peux voir clairement comment tout le monde devrait contribuer. Mais les gens ne sont pas des ressources — ils ont des besoins, des émotions et des rythmes. Les meilleurs leaders le savent.", exercice:"Pense à quelqu'un dans ton équipe ou entourage que tu ne vois pas assez comme une personne entière." },
      { jour:14, phase:'projet', titre:"Ta zone de génie", conseil:"Entrepreneuriat, direction générale, stratégie, finance, law, politique — partout où la vision long terme et l'exécution décisive sont la valeur clé, tu génères un impact rare.", exercice:"Dans quel domaine génères-tu naturellement des résultats que les autres peinent à obtenir ?" },
      { jour:15, phase:'projet', titre:"Ton prochain pas", conseil:"Tu sais déjà ce que tu veux faire. Le vrai défi : t'assurer que ce que tu construis est aligné avec ce que tu VEUX vraiment — pas juste ce que tu penses devoir accomplir.", exercice:"Vérifie : ton prochain grand objectif est-il le tien vraiment ? Ou celui que la société attend de toi ?" },
    ],
  },

  ENTP: {
    typeCode: 'ENTP', typeName: 'Le Débatteur', emoji: '⚡',
    intro: "En tant qu'ENTP, tu es un générateur d'idées et un challenger naturel. Ce programme t'aide à transformer ton énergie intellectuelle en création concrète, à mieux vivre tes relations et à choisir tes batailles.",
    jours: [
      { jour:1, phase:'moi', titre:"Ton esprit de contradiction", conseil:"Tu questionnes les idées reçues par réflexe. Ce n'est pas de l'arrogance — c'est un besoin de tester la solidité des arguments. Mais débattre constamment peut épuiser ceux qui n'ont pas ta réserve d'énergie intellectuelle.", exercice:"Identifie 1 débat que tu as lancé récemment. Était-ce pour trouver la vérité ou pour le plaisir du jeu ?" },
      { jour:2, phase:'moi', titre:"Ton appétit d'idées", conseil:"Tu t'ennuies rapidement de ce que tu as déjà compris. La nouveauté intellectuelle est ton carburant. Ce besoin est légitime — et il peut aussi te faire abandonner des projets dès que le défi initial est résolu.", exercice:"Identifie 1 domaine que tu as exploré puis abandonné. Qu'est-ce qui avait déclenché l'intérêt ? Et l'arrêt ?" },
      { jour:3, phase:'moi', titre:"Ton rapport aux règles", conseil:"Les règles arbitraires te semblent des obstacles inutiles. Tu les questionnes instinctivement. C'est une force d'innovation — et une source de conflits quand les règles en question ont une raison légitime.", exercice:"Identifie 1 règle que tu contournes régulièrement. A-t-elle une raison valable que tu n'as pas considérée ?" },
      { jour:4, phase:'moi', titre:"Ton angle mort émotionnel", conseil:"Tu tends à analyser les situations émotionnelles plutôt qu'à les ressentir. Ça te protège mais peut te faire passer pour insensible aux yeux des autres, même quand tu essaies d'aider.", exercice:"La prochaine fois que quelqu'un partage quelque chose d'émotionnel, écoute avant d'analyser. Juste écouter." },
      { jour:5, phase:'moi', titre:"Comment tu te ressources", conseil:"Tu te ressources dans les conversations stimulantes, les nouveaux défis intellectuels et l'exploration de nouvelles idées. La routine pure te consomme lentement même si elle semble efficace.", exercice:"Identifie ton dernier moment de vraie stimulation intellectuelle. Quand est-ce arrivé ?" },
      { jour:6, phase:'relations', titre:"Ton charme intellectuel", conseil:"Tu peux captiver avec les idées et la conversation. Mais les relations profondes demandent aussi une présence émotionnelle et une vulnérabilité que l'intelligence seule ne peut pas remplacer.", exercice:"Pense à une relation importante. Est-ce que tu te montres émotionnellement, pas juste intellectuellement ?" },
      { jour:7, phase:'relations', titre:"Ce que tu cherches", conseil:"Tu cherches quelqu'un qui peut tenir ta vitesse intellectuelle et te challenger — quelqu'un que tu ne peux pas facilement 'battre' dans une conversation. Mais aussi quelqu'un qui te voit au-delà de ton intelligence.", exercice:"Dans tes relations actuelles, qui te challenge vraiment intellectuellement ? Et qui te voit vraiment ?" },
      { jour:8, phase:'relations', titre:"Ton débat comme blessure", conseil:"Tu peux débattre avec quelqu'un que tu respectes et qu'il se sente attaqué, alors que pour toi c'est juste une conversation stimulante. Ce décalage peut endommager des relations auxquelles tu tiens.", exercice:"Rappelle-toi 1 conversation où l'autre semblait blessé alors que tu discutais juste. Qu'as-tu raté ?" },
      { jour:9, phase:'relations', titre:"Tes compatibilités", conseil:"Les INTJ, INFJ et ENFJ te complètent bien — ils apportent la profondeur et la structure qui donnent de la forme à tes idées. Les ENTJ partagent ton ambition et ta vitesse.", exercice:"Pense à quelqu'un qui transforme tes idées en action. Comment nourrir ce partenariat ?" },
      { jour:10, phase:'relations', titre:"Comment tu aimes", conseil:"Tu aimes en stimulant intellectuellement l'autre, en l'exposant à de nouvelles idées et en challengeant sa façon de voir le monde pour le/la faire grandir. C'est un amour rare — mais l'autre a aussi besoin de douceur.", exercice:"Fais quelque chose de doux et simple pour quelqu'un qui compte cette semaine. Pas brillant. Juste doux." },
      { jour:11, phase:'projet', titre:"Ton environnement idéal", conseil:"Liberté intellectuelle, nouveaux défis et absence de routine rigide — c'est là que tu génères ta valeur maximale. L'exécution répétitive et les tâches administratives te vident sans créer de valeur pour toi.", exercice:"Identifie 3 tâches dans ta vie qui pourraient être déléguées ou automatisées pour libérer ton énergie." },
      { jour:12, phase:'projet', titre:"Tes idées non atterries", conseil:"Tu génères des idées brillantes régulièrement. Le problème : tu en génères trop pour toutes les exécuter. L'art est de choisir la meilleure et de la pousser jusqu'au bout au lieu de passer à la suivante.", exercice:"Identifie l'idée qui a le plus de potentiel parmi celles que tu as en tête. Juste une." },
      { jour:13, phase:'projet', titre:"Ta résistance à l'exécution", conseil:"La phase de conception est passionnante. La phase d'exécution répétitive l'est moins. Mais sans exécution, tes idées ne changent rien. L'exécution est le service que tu rends à ta propre intelligence.", exercice:"Identifie 1 idée que tu as depuis plus de 3 mois sans agir. Qu'est-ce qui t'en empêche vraiment ?" },
      { jour:14, phase:'projet', titre:"Ta zone de génie", conseil:"Entrepreneuriat, droit, stratégie d'innovation, conseil, recherche — partout où questionner les hypothèses existantes et générer des solutions non-conventionnelles est la valeur principale.", exercice:"Dans quel contexte as-tu résolu un problème d'une façon que personne d'autre n'avait envisagée ?" },
      { jour:15, phase:'projet', titre:"Ton prochain pas", conseil:"Ton intelligence ne manque pas. Ta direction non plus, au fond. Ce qu'il te faut : choisir et tenir. Cette semaine, un projet, une direction, et tu tiens jusqu'à la fin sans te disperser.", exercice:"Choisis ton projet le plus important. Fais 3 actions concrètes dessus avant dimanche soir." },
    ],
  },

  ESFJ: {
    typeCode: 'ESFJ', typeName: 'Le Consul', emoji: '🤝',
    intro: "En tant qu'ESFJ, tu es le ciment social de ton entourage. Ce programme t'aide à prendre soin de toi autant que tu prends soin des autres, à nourrir tes propres besoins et à trouver l'équilibre entre soin et affirmation de soi.",
    jours: [
      { jour:1, phase:'moi', titre:"Ton rôle de ciment social", conseil:"Tu maintiens les liens, organises les rassemblements et t'assures que tout le monde va bien. C'est un don précieux. Mais si tu disparais, le groupe se souvient de ce qu'il perdait — et toi tu avais tout donné.", exercice:"Identifie ce que tu apportes à ton cercle social. Est-ce que les autres te le rendent en nature ?" },
      { jour:2, phase:'moi', titre:"Ton besoin d'approbation", conseil:"Tu es profondément affecté(e) par la désapprobation des autres, même de personnes qui ne comptent pas vraiment pour toi. Ta valeur ne se trouve pas dans le regard des autres — elle est intrinsèque.", exercice:"Rappelle-toi 1 critique récente qui t'a touché(e). Était-elle importante ? De qui venait-elle ?" },
      { jour:3, phase:'moi', titre:"Ta difficulté à dire non", conseil:"Dire non te semble souvent égoïste. Mais chaque oui que tu donnes à contrecœur vide une batterie que tu recharges difficilement. Ta générosité reste entière même quand tu poses des limites.", exercice:"Dis non à une demande cette semaine. Sans excuses élaborées. 'Je ne peux pas cette fois.' C'est tout." },
      { jour:4, phase:'moi', titre:"Tes attentes non verbalisées", conseil:"Tu donnes énormément et tu attends souvent que les autres le remarquent et le rendent sans que tu aies à le demander. Cette attente silencieuse est la source de beaucoup de tes déceptions.", exercice:"Exprime 1 besoin ou attente directement à quelqu'un, sans sous-entendus. Observe ce qui se passe." },
      { jour:5, phase:'moi', titre:"Comment tu te ressources", conseil:"Tu te ressources dans les relations chaleureuses et les environnements familiers. Mais tu peux aussi te vider à force de prendre soin des autres sans jamais recevoir le même niveau de soin.", exercice:"Identifie 1 façon dont tu pourrais prendre soin de toi cette semaine sans que ça implique les autres." },
      { jour:6, phase:'relations', titre:"Ton style de soin", conseil:"Tu exprimes l'amour en cuisinant, en organisant, en te souvenant des anniversaires et en étant là dans les moments importants. C'est du soin concret — mais certains ne voient pas ce langage d'amour.", exercice:"Dis à voix haute à quelqu'un comment tu exprimes ton affection. Aide-les à voir ce que tu fais pour eux." },
      { jour:7, phase:'relations', titre:"Ce que tu cherches", conseil:"Tu cherches quelqu'un qui reconnaît tes efforts, partage tes valeurs d'engagement et prend soin de toi en retour. La réciprocité n'est pas un luxe — c'est ce qui te permet de continuer à donner.", exercice:"Dans tes relations actuelles, qui prend soin de toi autant que tu prends soin d'eux ?" },
      { jour:8, phase:'relations', titre:"Tes conflits évités", conseil:"Tu maintiens l'harmonie parfois au détriment de ta propre vérité. Les conflits évités s'accumulent et ressortent souvent de façon disproportionnée. Exprimer tôt, doucement, protège les relations.", exercice:"Identifie 1 frustration gardée depuis trop longtemps. Comment la dire avec bienveillance aujourd'hui ?" },
      { jour:9, phase:'relations', titre:"Tes compatibilités", conseil:"Les ISFJ, ISTJ et ENFJ partagent souvent tes valeurs de soin et d'engagement. Les ESTP et ENFP apportent de la spontanéité qui peut enrichir ta tendance à planifier et organiser.", exercice:"Pense à quelqu'un qui te sort de ta routine. Qu'est-ce que ça t'apporte concrètement ?" },
      { jour:10, phase:'relations', titre:"Comment tu aimes", conseil:"Tu aimes en faisant — cuisine, organisation, présence, soutien pratique. C'est un langage d'amour puissant mais discret. Assure-toi aussi de le dire parfois en mots directs.", exercice:"Dis à quelqu'un qui compte précisément ce que tu fais pour lui/elle et pourquoi." },
      { jour:11, phase:'projet', titre:"Ton environnement idéal", conseil:"Tu travailles mieux dans des équipes soudées avec des rôles clairs et une atmosphère de coopération. Les environnements compétitifs et froids te vident de ton énergie rapidement.", exercice:"Qu'est-ce qui dans ton environnement actuel crée de la chaleur humaine ? Qu'est-ce qui l'enfreint ?" },
      { jour:12, phase:'projet', titre:"Tes ambitions relationnelles", conseil:"Tes ambitions sont souvent liées aux personnes plutôt qu'aux chiffres ou aux titres. Tu veux créer quelque chose qui serve vraiment les gens. C'est un moteur puissant et souvent sous-estimé.", exercice:"Décris l'impact humain que tu veux avoir dans 3 ans. Pas les postes ou revenus — l'impact sur les gens." },
      { jour:13, phase:'projet', titre:"Ta peur du changement", conseil:"Tu préfères la stabilité à l'incertitude. Le changement peut perturber les relations que tu as construites soigneusement. Mais certains changements sont nécessaires pour grandir et te renouveler.", exercice:"Identifie 1 changement que tu as évité par peur de perturber tes relations. Était-ce la bonne décision ?" },
      { jour:14, phase:'projet', titre:"Ta zone de génie", conseil:"RH, enseignement, soin, gestion de communauté, événementiel, diplomatie — partout où créer et maintenir des liens humains de qualité est la compétence clé, tu excelles naturellement.", exercice:"Dans quel rôle les gens te font-ils confiance instinctivement pour 'gérer les relations' ?" },
      { jour:15, phase:'projet', titre:"Ton prochain pas", conseil:"Tu prends si bien soin des autres que tu t'oublies parfois. Cette semaine, quel est TON prochain pas — pour tes propres ambitions, ton propre développement, ta propre vie ?", exercice:"Identifie 1 objectif personnel que tu remets à plus tard parce que tu t'occupes des autres. Commence maintenant." },
    ],
  },

  ESFP: {
    typeCode: 'ESFP', typeName: "L'Animateur", emoji: '🎉',
    intro: "En tant qu'ESFP, tu vis avec une intensité et une joie de vivre rares. Ce programme t'aide à approfondir ce qui compte, à mieux gérer le long terme et à transformer ton énergie naturelle en quelque chose de durable.",
    jours: [
      { jour:1, phase:'moi', titre:"Ton énergie vitale", conseil:"Tu apportes de la vie partout où tu vas. Les gens se souviennent de toi. C'est un don extraordinaire — mais il demande aussi une gestion de ton énergie pour ne pas te vider en cherchant à tout animer.", exercice:"Identifie les situations qui te donnent de l'énergie vs celles qui t'en prennent. Qu'est-ce que ça révèle ?" },
      { jour:2, phase:'moi', titre:"Le présent comme force", conseil:"Tu es pleinement dans l'instant comme peu de gens peuvent l'être. Tu ressens, tu réagis, tu crées dans le moment. Cette présence est précieuse — et peut parfois créer des défis sur le long terme.", exercice:"Identifie 1 domaine où vivre dans le présent t'a coûté quelque chose sur le long terme." },
      { jour:3, phase:'moi', titre:"Ton évitement du négatif", conseil:"Tu préfères naturellement focus sur le positif. C'est une force. Mais éviter systématiquement les émotions difficiles ou les conversations sérieuses peut laisser des problèmes non résolus s'accumuler.", exercice:"Identifie 1 situation difficile que tu évites. Qu'est-ce qui se passerait si tu l'affrontais directement ?" },
      { jour:4, phase:'moi', titre:"Ta sensibilité cachée", conseil:"Sous ton enthousiasme visible se cache une sensibilité profonde. Tu peux être blessé(e) plus facilement que tu ne le montres. Et tu guéris parfois en cherchant plus de distractions plutôt qu'en traitant la blessure.", exercice:"Identifie 1 blessure récente que tu as 'oubliée' en te distrayant. Est-ce qu'elle est vraiment guérie ?" },
      { jour:5, phase:'moi', titre:"Comment tu te ressources", conseil:"Tu te ressources dans l'action, la musique, les gens et les expériences sensorielles fortes. La solitude prolongée et l'abstraction te pèsent. Respecter ce rythme est ta façon d'exister pleinement.", exercice:"Identifie ton activité de ressourcement préférée. Est-ce que tu te la donnes assez souvent ?" },
      { jour:6, phase:'relations', titre:"Ton charme naturel", conseil:"Tu mets les gens à l'aise instantanément. Tu crées une atmosphère chaleureuse sans effort apparent. C'est un don social rare — mais les relations profondes demandent aussi de la profondeur, pas juste de la légèreté.", exercice:"Pense à ta relation la plus profonde. Qu'est-ce qui la rend profonde au-delà du plaisir d'être ensemble ?" },
      { jour:7, phase:'relations', titre:"Ce que tu cherches", conseil:"Tu cherches quelqu'un qui partage ton goût pour la vie, les expériences et le plaisir d'être ensemble — mais qui peut aussi t'ancrer quand tu as besoin de stabilité sans t'étouffer.", exercice:"Dans tes relations actuelles, qui t'apporte à la fois de la légèreté ET de la stabilité ?" },
      { jour:8, phase:'relations', titre:"Ton engagement à long terme", conseil:"L'engagement sur le long terme peut sembler moins naturel quand tu es si orienté(e) vers le présent. Mais les relations profondes se construisent dans la durée — elles demandent d'y revenir même quand ce n'est pas toujours excitant.", exercice:"Identifie 1 relation importante que tu as peut-être négligée récemment. Reprends contact cette semaine." },
      { jour:9, phase:'relations', titre:"Tes compatibilités", conseil:"Les ISFP, ISTJ et ESFJ partagent souvent ton attachement au concret et au soin. Les ENFP et ENTP apportent de l'énergie intellectuelle qui peut enrichir ton goût pour l'expérience.", exercice:"Pense à quelqu'un qui t'apporte quelque chose que tu n'as pas naturellement. Qu'est-ce que c'est ?" },
      { jour:10, phase:'relations', titre:"Comment tu aimes", conseil:"Tu aimes en créant des moments, en étant entièrement présent(e) et en apportant de la joie concrète. C'est un langage d'amour vivant et chaleureux — qui mérite aussi d'être dit explicitement parfois.", exercice:"Dis à quelqu'un qui compte ce que tu ressens pour lui/elle. En mots directs, pas juste en gestes." },
      { jour:11, phase:'projet', titre:"Ton environnement idéal", conseil:"Interaction humaine, variété et action concrète — c'est ton terrain. Les bureaux silencieux, les tâches abstraites et le travail solitaire prolongé te consument rapidement.", exercice:"Décris l'environnement dans lequel tu as été le/la plus productif(ve) et heureux(se). Qu'avait-il de particulier ?" },
      { jour:12, phase:'projet', titre:"Tes projets instantanés", conseil:"Tu démarre vite et tu peux t'essouffler sur la durée. Ce n'est pas une faiblesse — c'est une invitation à trouver des systèmes qui maintiennent ton énergie sur des projets plus longs.", exercice:"Identifie 1 projet long terme que tu as abandonné. Qu'est-ce qui avait éteint ton énergie ?" },
      { jour:13, phase:'projet', titre:"Ton horizon court terme", conseil:"Penser à long terme est moins naturel pour toi. Mais quelques repères clairs à 6-12 mois peuvent libérer ton énergie quotidienne plutôt que la contraindre.", exercice:"Décris à quoi ressemble ta situation idéale dans 6 mois. Juste les grandes lignes, en 3 phrases." },
      { jour:14, phase:'projet', titre:"Ta zone de génie", conseil:"Performance, vente, entertainment, tourisme, restauration, événementiel, coiffure, mode — partout où l'énergie humaine, le sens esthétique et la présence sont la valeur principale, tu brilles.", exercice:"Dans quel domaine les gens te disent-ils 'tu as un don naturel pour ça' ? C'est souvent là." },
      { jour:15, phase:'projet', titre:"Ton prochain pas", conseil:"L'ESFP a tout pour réussir — énergie, charme, présence. Ce qu'il lui faut : un cap assez motivant pour tenir plus de quelques semaines. Cette semaine, choisis UN cap. Et tiens-le.", exercice:"Identifie 1 objectif qui te motive vraiment pour les 3 prochains mois. Note-le. Lis-le chaque matin." },
    ],
  },

  ESTJ: {
    typeCode: 'ESTJ', typeName: 'Le Directeur', emoji: '📊',
    intro: "En tant qu'ESTJ, tu combines rigueur, efficacité et sens des responsabilités comme peu le font. Ce programme t'aide à comprendre ta relation aux émotions, à enrichir tes connexions et à diriger avec autant de cœur que de structure.",
    jours: [
      { jour:1, phase:'moi', titre:"Ta rigueur comme force", conseil:"Tu fais les choses correctement parce que c'est la bonne façon de les faire. Ta fiabilité et ton sens des responsabilités créent de la confiance autour de toi — une valeur rare dans un monde d'approximation.", exercice:"Identifie 3 domaines où ta rigueur crée une valeur que les autres ne peuvent pas reproduire facilement." },
      { jour:2, phase:'moi', titre:"Ta rigidité comme risque", conseil:"Ton attachement aux règles et aux procédures est une force — jusqu'au moment où le contexte change et que la règle n'est plus adaptée. Distinguer la règle utile de la règle habitude est une compétence clé.", exercice:"Identifie 1 règle que tu appliques par habitude. Serait-elle toujours pertinente si tu la questionnais ?" },
      { jour:3, phase:'moi', titre:"Tes émotions au travail", conseil:"Tu tends à voir les émotions comme des éléments perturbateurs de l'efficacité. Mais les émotions sont de l'information — sur toi, sur les autres, sur ce qui ne fonctionne pas. Les ignorer coûte cher à long terme.", exercice:"Identifie 1 émotion que tu as ressentie cette semaine et que tu as mise de côté pour 'être efficace'." },
      { jour:4, phase:'moi', titre:"Ton besoin de contrôle", conseil:"Tu te sens mieux quand tu as le contrôle sur les processus et les résultats. Ce besoin est compréhensible — mais il peut créer des tensions quand les autres ont leurs propres façons de faire, tout aussi valides.", exercice:"Identifie 1 situation où tu as insisté sur 'ta façon'. Aurait-il pu y avoir une autre façon valide ?" },
      { jour:5, phase:'moi', titre:"Comment tu te ressources", conseil:"Tu te ressources dans l'accomplissement concret et les routines structurées. L'ambiguïté et le chaos prolongés te consument. Clarifier tes priorités régulièrement te permet de recharger efficacement.", exercice:"Identifie ta routine de ressourcement la plus efficace. La respectes-tu vraiment ?" },
      { jour:6, phase:'relations', titre:"Ton style direct", conseil:"Tu communiques clairement et directement. C'est une qualité. Mais ce qui est directe pour toi peut sembler brutal pour d'autres. Le delivery compte autant que le message dans les relations.", exercice:"Rappelle-toi 1 conversation où ton directness a semblé blesser quelqu'un. Qu'aurais-tu pu changer ?" },
      { jour:7, phase:'relations', titre:"Ce que tu cherches", conseil:"Tu cherches quelqu'un de fiable, responsable et engagé — quelqu'un dont les actes correspondent aux paroles. La cohérence et l'intégrité sont des exigences non-négociables pour toi.", exercice:"Dans tes relations proches, qui est le plus cohérent entre ce qu'il dit et ce qu'il fait ?" },
      { jour:8, phase:'relations', titre:"Tes attentes non dites", conseil:"Tu peux avoir des attentes élevées envers les autres sans les avoir explicitées. Puis tu es frustré(e) quand ils ne les remplissent pas. Mais une attente non dite est une déception prévisible.", exercice:"Identifie 1 attente que tu as envers quelqu'un et que tu n'as jamais clairement exprimée." },
      { jour:9, phase:'relations', titre:"Tes compatibilités", conseil:"Les ISTJ, ESFJ et ENTJ partagent souvent tes valeurs d'efficacité et d'engagement. Les INFP et ENFP t'apportent de la créativité et une perspective différente qui peut enrichir ta vision.", exercice:"Pense à quelqu'un très différent de toi avec qui tu travailles bien. Qu'est-ce que vous apportez l'un à l'autre ?" },
      { jour:10, phase:'relations', titre:"Comment tu aimes", conseil:"Tu aimes en étant fiable, en tenant tes engagements et en construisant quelque chose de concret et durable. C'est un amour solide — mais certains ont aussi besoin de mots et de gestes spontanés.", exercice:"Fais quelque chose de spontané et d'affectueux cette semaine pour quelqu'un qui compte. Sans agenda." },
      { jour:11, phase:'projet', titre:"Ton environnement idéal", conseil:"Structure claire, rôles définis et processus efficaces — c'est là que tu génères ton impact maximum. Le chaos organisationnel et l'ambiguïté permanente te font perdre de l'énergie inutilement.", exercice:"Liste 3 améliorations de ton environnement de travail qui augmenteraient immédiatement ton efficacité." },
      { jour:12, phase:'projet', titre:"Tes ambitions concrètes", conseil:"Tes ambitions sont souvent concrètes et mesurables. C'est une force — les objectifs vagues restent des vœux. Mais assure-toi que tes objectifs sont AUSSI alignés avec ce que tu veux vraiment, pas juste ce que tu 'devrais' vouloir.", exercice:"Ton prochain grand objectif est-il vraiment le tien ? Ou celui que tu penses devoir avoir ?" },
      { jour:13, phase:'projet', titre:"Ta résistance au changement", conseil:"Tu te méfies des changements sans preuves de leur efficacité. C'est souvent sage. Mais parfois le changement arrive même si tu ne l'as pas choisi — et ta capacité d'adaptation détermine ta résilience.", exercice:"Identifie 1 changement récent que tu as mal accueilli. Avec le recul, y a-t-il une opportunité là-dedans ?" },
      { jour:14, phase:'projet', titre:"Ta zone de génie", conseil:"Management, administration, finance, droit, armée, politique — partout où la rigueur, la structure et la responsabilité sont des valeurs fondamentales, tu excelles naturellement.", exercice:"Dans quel rôle les gens te confient-ils instinctivement des responsabilités importantes ?" },
      { jour:15, phase:'projet', titre:"Ton prochain pas", conseil:"Tu sais planifier et exécuter. Cette semaine, applique ces forces à quelque chose qui compte pour TOI personnellement — pas juste tes responsabilités. Ta propre vie mérite aussi ta rigueur.", exercice:"Identifie 1 objectif personnel que tu reports depuis trop longtemps. Crée un plan simple en 3 étapes." },
    ],
  },

  ESTP: {
    typeCode: 'ESTP', typeName: "L'Entrepreneur", emoji: '🚀',
    intro: "En tant qu'ESTP, tu combines action immédiate, charme naturel et intelligence pratique. Ce programme t'aide à mieux comprendre tes relations, à construire sur le long terme et à canaliser ton énergie vers ce qui dure.",
    jours: [
      { jour:1, phase:'moi', titre:"Ton énergie d'action", conseil:"Tu agis là où les autres analysent encore. C'est ta plus grande force — tu crées du mouvement, tu résous des problèmes en temps réel et tu t'adaptes plus vite que quiconque.", exercice:"Identifie 1 situation récente où ton action rapide a créé un résultat que l'analyse n'aurait pas obtenu." },
      { jour:2, phase:'moi', titre:"Ton rapport au risque", conseil:"Tu es à l'aise avec le risque là où les autres hésitent. Cette tolérance est une compétence entrepreneuriale rare. Mais le risque calculé et le risque impulsif sont deux choses différentes.", exercice:"Rappelle-toi 1 risque que tu as pris. Était-il calculé ou impulsif ? Qu'est-ce que ça a donné ?" },
      { jour:3, phase:'moi', titre:"Ton ennui comme déclencheur", conseil:"L'ennui est pour toi un signal d'alarme fort. Quand tu t'ennuies, tu prends des risques ou tu cherches de la nouveauté — parfois de façon utile, parfois de façon destructrice pour ce que tu as construit.", exercice:"Qu'est-ce qui t'ennuie en ce moment ? Comment peux-tu y répondre de façon constructive ?" },
      { jour:4, phase:'moi', titre:"Tes émotions en mouvement", conseil:"Tu traites les émotions en action plutôt qu'en réflexion. Ce mode de traitement est légitime — mais certaines situations demandent de s'arrêter et de ressentir avant d'agir.", exercice:"Identifie 1 émotion difficile que tu as 'traitée' en passant à l'action. Était-ce vraiment résolu ?" },
      { jour:5, phase:'moi', titre:"Comment tu te ressources", conseil:"Tu te ressources dans l'action, le mouvement et les expériences sensorielles fortes. L'immobilité prolongée te pèse physiquement. Respecter ce rythme n'est pas de la superficialité — c'est ton mode de fonctionnement.", exercice:"Identifie ton activité de ressourcement la plus efficace. Est-ce que tu te l'accordes assez souvent ?" },
      { jour:6, phase:'relations', titre:"Ton charme pratique", conseil:"Tu peux captiver avec ta présence, ton humour et ta capacité à créer une atmosphère. Mais les relations profondes demandent plus que du charme — elles demandent de la constance et de la vulnérabilité.", exercice:"Pense à ta relation la plus proche. Qu'est-ce qui la rend profonde au-delà du plaisir d'être ensemble ?" },
      { jour:7, phase:'relations', titre:"Ce que tu cherches", conseil:"Tu cherches quelqu'un qui partage ton goût pour l'action et les expériences — et qui peut aussi t'ancrer sans t'étouffer. Quelqu'un d'autonome qui ne freine pas ton énergie.", exercice:"Dans tes relations actuelles, qui respecte le plus ta liberté tout en t'apportant de la profondeur ?" },
      { jour:8, phase:'relations', titre:"Ton engagement dans la durée", conseil:"L'engagement long terme peut sembler contraignant quand tu vis si fortement dans le présent. Mais les relations qui durent se construisent dans la durée — elles méritent ton attention même quand elles ne sont pas excitantes.", exercice:"Identifie 1 relation importante que tu as peut-être négligée. Fais 1 geste concret cette semaine." },
      { jour:9, phase:'relations', titre:"Tes compatibilités", conseil:"Les ISTP, ESTP et ENTJ partagent souvent ton pragmatisme et ton goût pour l'action. Les INFJ et ISFJ t'apportent une profondeur émotionnelle qui peut t'enrichir si tu leur laisses la place.", exercice:"Pense à quelqu'un qui t'apporte de la profondeur émotionnelle. Comment valoriser ce qu'il/elle t'apporte ?" },
      { jour:10, phase:'relations', titre:"Comment tu aimes", conseil:"Tu aimes en étant là, en agissant pour l'autre, en résolvant ses problèmes concrets et en créant des moments mémorables ensemble. C'est un amour vivant et généreux.", exercice:"Fais quelque chose de concret et mémorable pour quelqu'un qui compte cette semaine." },
      { jour:11, phase:'projet', titre:"Ton environnement idéal", conseil:"Action, résultats visibles et liberté de trouver ta propre méthode — c'est là que tu génères ta valeur maximale. Les réunions sans fin, les procédures rigides et le travail administratif te consument.", exercice:"Identifie 3 tâches dans ta vie qui t'épuisent sans te donner d'énergie en retour. Peut-on les déléguer ?" },
      { jour:12, phase:'projet', titre:"Tes projets à court terme", conseil:"Tu excelles dans l'exécution rapide. Le long terme te semble parfois moins réel. L'art est de trouver des projets longs qui se déclinent en sprints courts pour maintenir ton énergie.", exercice:"Identifie 1 projet long terme. Comment le découper en étapes de 1 semaine maximum ?" },
      { jour:13, phase:'projet', titre:"Ton horizon futur", conseil:"Penser à 2-3 ans semble parfois abstrait. Mais quelques repères clairs libèrent ton énergie quotidienne plutôt que de la contraindre. Un cap, pas un plan rigide.", exercice:"Décris ta situation idéale dans 2 ans en 3 phrases. Vague, c'est bien. L'important est de noter quelque chose." },
      { jour:14, phase:'projet', titre:"Ta zone de génie", conseil:"Entrepreneuriat, vente, négociation, urgences, trading, sport, politique — partout où l'action rapide, l'adaptation au réel et le charme sont les compétences clés, tu es dans ta zone.", exercice:"Dans quel contexte génères-tu naturellement des résultats que les autres peinent à obtenir ?" },
      { jour:15, phase:'projet', titre:"Ton prochain pas", conseil:"Tu as l'énergie, le charme et la capacité d'action. Ce qu'il te faut : un cap assez motivant pour valoir l'effort de le tenir dans la durée. Cette semaine, choisis ton cap — et tiens-le 30 jours.", exercice:"Identifie 1 objectif important. Engage-toi à y travailler 20 minutes par jour pendant 30 jours. Commence aujourd'hui." },
    ],
  },

};

export function getSuivi(typeCode: string): SuiviData | null {
  return db[typeCode.toUpperCase()] ?? null;
}

export function getAllSuiviTypes(): string[] {
  return Object.keys(db);
}

export const PHASE_LABELS: Record<SuiviJour['phase'], string> = {
  moi: '🧠 Me connaître',
  relations: '💝 Mes relations',
  projet: '🎯 Mes projets',
};
